apiVersion: v1
kind: Pod
metadata : 
  name: nginx
  labels:
    app: nginx
    ex: first
spec: 
  containers:
    - name: nginx
      image: nginx
      resources: 
        limits:
          memory: "512MB"
          cpu: ".5"